// grep -r '^shared class [[:alpha:]]*(' source/ceylon/ast/core/ | grep -v 'Editor\|Visitor\|Transformer' | sed 's|.*class \([[:alpha:]]*\)(.*|    \1,|' | sort | xclip
import ceylon.ast.core {
    AddAssignmentOperation,
    AliasDec,
    AndAssignmentOperation,
    AndOperation,
    Annotation,
    Annotations,
    AnonymousArgument,
    ArgumentList,
    Assertion,
    AssignmentStatement,
    AssignOperation,
    BaseExpression,
    BaseMeta,
    BaseType,
    Block,
    BooleanCondition,
    Break,
    CallableParameter,
    CallableType,
    CaseClause,
    CaseTypes,
    CatchClause,
    CharacterLiteral,
    ClassAliasDefinition,
    ClassBody,
    ClassDec,
    ClassDefinition,
    ClassInstantiation,
    ClassSpecifier,
    ClosedBound,
    CompareOperation,
    CompilationUnit,
    ComplementAssignmentOperation,
    ComplementOperation,
    Comprehension,
    Conditions,
    Continue,
    DecQualifier,
    DefaultedCallableParameter,
    DefaultedParameterReference,
    DefaultedType,
    DefaultedValueParameter,
    DifferenceOperation,
    DivideAssignmentOperation,
    DynamicBlock,
    DynamicInterfaceDefinition,
    DynamicModifier,
    DynamicValue,
    ElementOrSubrangeExpression,
    ElseCaseClause,
    ElseClause,
    ElseOperation,
    EntryOperation,
    EntryType,
    EqualOperation,
    ExistsCondition,
    ExistsOperation,
    ExponentiationOperation,
    ExpressionComprehensionClause,
    ExtendedType,
    FailClause,
    FinallyClause,
    FloatLiteral,
    ForClause,
    ForComprehensionClause,
    ForFail,
    FullPackageName,
    FunctionArgument,
    FunctionDec,
    FunctionDeclaration,
    FunctionDefinition,
    FunctionExpression,
    FunctionModifier,
    FunctionShortcutDefinition,
    GivenDec,
    GroupedExpression,
    GroupedType,
    IdenticalOperation,
    IdentityOperation,
    IfClause,
    IfComprehensionClause,
    IfElse,
    Import,
    ImportElements,
    ImportFunctionValueAlias,
    ImportFunctionValueElement,
    ImportTypeAlias,
    ImportTypeElement,
    ImportWildcard,
    InModifier,
    InOperation,
    IntegerLiteral,
    InterfaceAliasDefinition,
    InterfaceBody,
    InterfaceDec,
    InterfaceDefinition,
    IntersectAssignmentOperation,
    IntersectionOperation,
    IntersectionType,
    Invocation,
    InvocationStatement,
    IsCase,
    IsCondition,
    IsOperation,
    Iterable,
    IterableType,
    KeySubscript,
    KeyValueIterator,
    LargeAsOperation,
    LargerOperation,
    LazySpecification,
    LazySpecifier,
    LIdentifier,
    MatchCase,
    MeasureOperation,
    MeasureSubscript,
    MemberMeta,
    MemberNameWithTypeArguments,
    MemberOperator,
    ModuleBody,
    ModuleCompilationUnit,
    ModuleDec,
    ModuleDescriptor,
    ModuleImport,
    MultiplyAssignmentOperation,
    NamedArguments,
    NegationOperation,
    NonemptyCondition,
    NonemptyOperation,
    NotEqualOperation,
    NotOperation,
    ObjectArgument,
    ObjectDefinition,
    OfOperation,
    OpenBound,
    OperatorStyleInvocation,
    OperatorStyleMemberExpression,
    OptionalType,
    OrAssignmentOperation,
    OrOperation,
    Outer,
    OutModifier,
    Package,
    PackageCompilationUnit,
    PackageDec,
    PackageDescriptor,
    ParameterReference,
    Parameters,
    PositionalArguments,
    PostfixDecrementOperation,
    PostfixIncrementOperation,
    PrefixDecrementOperation,
    PrefixIncrementOperation,
    PrefixPostfixStatement,
    ProductOperation,
    QualifiedExpression,
    QualifiedType,
    QuotientOperation,
    RemainderAssignmentOperation,
    RemainderOperation,
    Resource,
    Resources,
    Return,
    SafeMemberOperator,
    SatisfiedTypes,
    ScaleOperation,
    SequentialType,
    SmallAsOperation,
    SmallerOperation,
    SpanFromSubscript,
    SpanOperation,
    SpanSubscript,
    SpanToSubscript,
    SpecifiedArgument,
    SpecifiedVariable,
    Specifier,
    SpreadArgument,
    SpreadMemberOperator,
    StringLiteral,
    StringTemplate,
    SubtractAssignmentOperation,
    SumOperation,
    Super,
    SwitchCaseElse,
    SwitchCases,
    SwitchClause,
    ThenOperation,
    This,
    Throw,
    TryCatchFinally,
    TryClause,
    Tuple,
    TupleType,
    TypeAliasDefinition,
    TypeArgument,
    TypeArguments,
    TypeConstraint,
    TypedVariable,
    TypeList,
    TypeMeta,
    TypeNameWithTypeArguments,
    TypeParameter,
    TypeParameters,
    TypeSpecifier,
    UIdentifier,
    UnionAssignmentOperation,
    UnionOperation,
    UnionType,
    UnspecifiedVariable,
    ValueArgument,
    ValueDec,
    ValueDeclaration,
    ValueDefinition,
    ValueGetterDefinition,
    ValueIterator,
    ValueModifier,
    ValueParameter,
    ValueSetterDefinition,
    ValueSpecification,
    VariadicParameter,
    VariadicType,
    VoidModifier,
    While,
    WithinOperation
}

"A compilation unit node containing every AST node that can be a child of a regular compilation unit
 (that is, all nodes except those exclusively for module or package descriptors)."
// TODO expand until there are no more unused import warnings
CompilationUnit completeCompilationUnit
        = /* BEGIN */ CompilationUnit {
    imports = [
        Import {
            packageName = FullPackageName([
                    LIdentifier("java"),
                    LIdentifier("lang")
                ]);
            elements = ImportElements {
                elements = [
                    ImportTypeElement {
                        name = UIdentifier("System");
                        importAlias = ImportTypeAlias(UIdentifier("Sys"));
                        nestedImports = ImportElements {
                            elements = [
                                ImportFunctionValueElement {
                                    name = LIdentifier("out", true);
                                    importAlias = ImportFunctionValueAlias(LIdentifier("sysout"));
                                    nestedImports = null;
                                }
                            ];
                            wildcard = null;
                        };
                    }
                ];
                wildcard = ImportWildcard();
            };
        }
    ];
    declarations = [];
} /* END */;
