#!/bin/bash

if [[ $1 == --help || $1 == -h ]] || (($# < 2)); then
    printf 'Usage:\n$ %s AliasName CaseType1 CaseType2 ...\nDocumentation documentation\n\nExamples:\n\n    example code\n^D\n' "$0"
    exit 0
fi

ceylon run source_gen.ceylon.ast --alias "$@" || { ant csg; ceylon run source_gen.ceylon.ast --alias "$@"; }
